//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace InoxWind
{
    public partial class contact_details_of_kmp_for_determination_of_materiality_of_event_or_information
    {
    }
}
